package com.batch.demo.web;

import java.time.LocalDate;

import org.springframework.batch.core.job.Job;
import org.springframework.batch.core.job.JobExecution;
import org.springframework.batch.core.job.parameters.InvalidJobParametersException;
import org.springframework.batch.core.job.parameters.JobParameters;
import org.springframework.batch.core.job.parameters.JobParametersBuilder;
import org.springframework.batch.core.repository.explore.JobExplorer;
import org.springframework.batch.core.launch.JobExecutionAlreadyRunningException;
import org.springframework.batch.core.launch.JobExecutionNotRunningException;
import org.springframework.batch.core.launch.JobInstanceAlreadyCompleteException;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.core.launch.JobRestartException;
import org.springframework.batch.core.launch.NoSuchJobException;
import org.springframework.batch.core.launch.NoSuchJobExecutionException;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.batch.demo.batch.control.JobControlService;
import com.batch.demo.config.BatchProperties;
import com.batch.demo.web.dto.JobExecutionStatusResponse;
import com.batch.demo.web.dto.JobLaunchResponse;

/**
 * Deliberately thin: only launches the already-assembled {@link Job} bean, reports
 * status, and delegates stop/restart/abandon to {@link JobControlService}. No
 * job-building or exception-translation logic lives here (single responsibility).
 */
@RestController
@RequestMapping("/api/batch/jobs")
public class BatchJobController {

    private final JobLauncher jobLauncher;
    private final Job orderProcessingJob;
    private final Job dailyPipelineJob;
    private final JobExplorer jobExplorer;
    private final JobControlService jobControlService;
    private final BatchProperties batchProperties;

    /**
     * A hand-written constructor, not {@code @RequiredArgsConstructor}: {@code
     * @Qualifier} on a field is NOT copied onto Lombok's generated constructor
     * parameter (confirmed by decompiling the generated bytecode - no parameter
     * annotations at all end up on it), so a Lombok-generated constructor here would
     * silently keep resolving both Job-typed parameters to whichever bean is
     * {@code @Primary}. The qualifiers below are required, not decorative:
     * orderProcessingJob is marked {@code @Primary} (see BatchJobConfig) so
     * JobLauncherTestUtils's ambiguous-type autowiring keeps working in every existing
     * test - but {@code @Primary} takes precedence over name-based matching for every
     * OTHER Job-typed injection point too, so without an explicit qualifier here,
     * dailyPipelineJob would silently receive the orderProcessingJob bean instead
     * (confirmed the hard way: /daily-pipeline was launching orderProcessingJob a
     * second time under a different identity, never dailyPipelineJob at all).
     */
    public BatchJobController(JobLauncher jobLauncher,
                               @Qualifier("orderProcessingJob") Job orderProcessingJob,
                               @Qualifier("dailyPipelineJob") Job dailyPipelineJob,
                               JobExplorer jobExplorer,
                               JobControlService jobControlService,
                               BatchProperties batchProperties) {
        this.jobLauncher = jobLauncher;
        this.orderProcessingJob = orderProcessingJob;
        this.dailyPipelineJob = dailyPipelineJob;
        this.jobExplorer = jobExplorer;
        this.jobControlService = jobControlService;
        this.batchProperties = batchProperties;
    }

    @PostMapping("/order-processing")
    public ResponseEntity<JobLaunchResponse> launch(
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate businessDate)
            throws JobExecutionAlreadyRunningException, JobRestartException,
            JobInstanceAlreadyCompleteException, InvalidJobParametersException {
        // businessDate is part of what identifies a JobInstance (see Idempotency in
        // CLAUDE.md) - defaulting to today means a same-day relaunch is correctly
        // rejected as a duplicate, but also means manual/local re-testing on the same
        // day has no way to get a fresh JobInstance without this override.
        JobParameters jobParameters = new JobParametersBuilder()
                .addLocalDate("businessDate", businessDate != null ? businessDate : LocalDate.now())
                .addString("inputFile", batchProperties.getInputCsvPath())
                .addLong("startedAtEpochMs", System.currentTimeMillis(), false)
                .toJobParameters();

        JobExecution execution = jobLauncher.run(orderProcessingJob, jobParameters);

        return ResponseEntity.ok(new JobLaunchResponse(
                execution.getId(),
                execution.getStatus().name(),
                execution.getStartTime()));
    }

    /**
     * Orchestrates orderProcessingJob followed by dailySalesReportJob via JobStep (see
     * DailyPipelineJobConfig) - still launched through the plain JobLauncher exactly
     * like /order-processing; JobOperator is only ever used internally, by the two
     * JobSteps, to launch the nested jobs.
     *
     * Note a real gotcha, confirmed via the actual stack trace (not assumed): calling
     * this for a businessDate already covered by a standalone /order-processing run
     * does NOT 409 the way two /order-processing calls would - the orchestrator's own
     * JobInstance is new. Instead orderProcessingJobStep's nested
     * jobOperator.start(orderProcessingJob, ...) throws
     * JobInstanceAlreadyCompleteException, which AbstractStep.execute() catches and
     * logs ("Encountered an error executing step orderProcessingJobStep in job
     * dailyPipelineJob") rather than rethrowing - recording it as a failed
     * StepExecution instead of propagating out of this method. Net result: HTTP 200
     * with "status": "FAILED" in the body, not a 409 (see
     * DailyPipelineJobIdempotencyTest).
     */
    @PostMapping("/daily-pipeline")
    public ResponseEntity<JobLaunchResponse> launchDailyPipeline(
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate businessDate)
            throws JobExecutionAlreadyRunningException, JobRestartException,
            JobInstanceAlreadyCompleteException, InvalidJobParametersException {
        JobParameters jobParameters = new JobParametersBuilder()
                .addLocalDate("businessDate", businessDate != null ? businessDate : LocalDate.now())
                .addString("inputFile", batchProperties.getInputCsvPath())
                .addLong("startedAtEpochMs", System.currentTimeMillis(), false)
                .toJobParameters();

        JobExecution execution = jobLauncher.run(dailyPipelineJob, jobParameters);

        return ResponseEntity.ok(new JobLaunchResponse(
                execution.getId(),
                execution.getStatus().name(),
                execution.getStartTime()));
    }

    @GetMapping("/executions/{id}")
    public ResponseEntity<JobExecutionStatusResponse> getExecution(@PathVariable Long id) {
        JobExecution execution = jobExplorer.getJobExecution(id);
        if (execution == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(JobExecutionStatusResponse.from(execution));
    }

    @PostMapping("/executions/{id}/stop")
    public ResponseEntity<JobExecutionStatusResponse> stop(@PathVariable long id)
            throws NoSuchJobExecutionException, JobExecutionNotRunningException {
        return ResponseEntity.ok(jobControlService.stop(id));
    }

    @PostMapping("/executions/{id}/restart")
    public ResponseEntity<JobExecutionStatusResponse> restart(@PathVariable long id)
            throws JobInstanceAlreadyCompleteException, NoSuchJobExecutionException,
            NoSuchJobException, JobRestartException, InvalidJobParametersException {
        return ResponseEntity.ok(jobControlService.restart(id));
    }

    @PostMapping("/executions/{id}/abandon")
    public ResponseEntity<JobExecutionStatusResponse> abandon(@PathVariable long id)
            throws NoSuchJobExecutionException, JobExecutionAlreadyRunningException {
        return ResponseEntity.ok(jobControlService.abandon(id));
    }
}
