apiVersion: 1

datasources:
  - name: BatchDemo Postgres
    uid: batchdemo-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: batchdemo
    user: batchdemo
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: batchdemo
